Fixed AttributeError when attempting to destroy AWS instances
The provider argument provided is of type Providers enum which has no upper function.

The error produced was

AttributeError: 'Providers' object has no attribute 'upper'

Ticket: ENT-13656
Changelog: title

Co-authored-by: Ole Herman Schumacher Elgesem <4048546+olehermanse@users.noreply.github.com>